# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("movers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("period_start", models.DateField(verbose_name="period start")),
                ("period_end", models.DateField(verbose_name="period end")),
                (
                    "order_count",
                    models.PositiveIntegerField(default=0, verbose_name="order count"),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total quantity"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity_stats",
                        to="movers.itemtype",
                        verbose_name="item type",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popular_items",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "popular item",
                "verbose_name_plural": "popular items",
                "db_table": "popular_items",
                "ordering": ["-order_count"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Order Created"),
                            ("order_approved", "Order Approved"),
                            ("order_completed", "Order Completed"),
                            ("order_cancelled", "Order Cancelled"),
                            ("quote_created", "Quote Created"),
                            ("quote_sent", "Quote Sent"),
                            ("quote_viewed", "Quote Viewed"),
                            ("quote_accepted", "Quote Accepted"),
                            ("quote_rejected", "Quote Rejected"),
                            ("booking_created", "Booking Created"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_completed", "Booking Completed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("subscription_started", "Subscription Started"),
                            ("subscription_renewed", "Subscription Renewed"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("ai_parsing_used", "AI Parsing Used"),
                            ("ai_image_analyzed", "AI Image Analyzed"),
                            ("user_registered", "User Registered"),
                            ("user_login", "User Login"),
                        ],
                        max_length=50,
                        verbose_name="event type",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monetary value if applicable",
                        max_digits=12,
                        null=True,
                        verbose_name="value",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "event_date",
                    models.DateField(db_index=True, verbose_name="event date"),
                ),
                ("event_time", models.TimeField(verbose_name="event time")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "analytics event",
                "verbose_name_plural": "analytics events",
                "db_table": "analytics_events",
                "ordering": ["-event_date", "-event_time"],
                "indexes": [
                    models.Index(
                        fields=["mover", "event_type"],
                        name="analytics_e_mover_i_0b37bf_idx",
                    ),
                    models.Index(
                        fields=["mover", "event_date"],
                        name="analytics_e_mover_i_984a0b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "orders_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orders received"
                    ),
                ),
                (
                    "orders_approved",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orders approved"
                    ),
                ),
                (
                    "orders_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orders completed"
                    ),
                ),
                (
                    "orders_cancelled",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orders cancelled"
                    ),
                ),
                (
                    "quotes_sent",
                    models.PositiveIntegerField(default=0, verbose_name="quotes sent"),
                ),
                (
                    "quotes_accepted",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quotes accepted"
                    ),
                ),
                (
                    "quotes_rejected",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quotes rejected"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "total_quote_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total quote value",
                    ),
                ),
                (
                    "bookings_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="bookings created"
                    ),
                ),
                (
                    "bookings_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="bookings completed"
                    ),
                ),
                (
                    "ai_parsing_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="AI parsing count"
                    ),
                ),
                (
                    "ai_image_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="AI image count"
                    ),
                ),
                (
                    "quote_acceptance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="quote acceptance rate",
                    ),
                ),
                (
                    "order_completion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="order completion rate",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analytics",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily analytics",
                "verbose_name_plural": "daily analytics",
                "db_table": "daily_analytics",
                "ordering": ["-date"],
                "unique_together": {("mover", "date")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                ("month", models.PositiveIntegerField(verbose_name="month")),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="total orders"),
                ),
                (
                    "completed_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed orders"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="average order value",
                    ),
                ),
                (
                    "total_quotes",
                    models.PositiveIntegerField(default=0, verbose_name="total quotes"),
                ),
                (
                    "accepted_quotes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="accepted quotes"
                    ),
                ),
                (
                    "quote_acceptance_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="quote acceptance rate",
                    ),
                ),
                (
                    "new_customers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="new customers"
                    ),
                ),
                (
                    "repeat_customers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="repeat customers"
                    ),
                ),
                (
                    "ai_requests",
                    models.PositiveIntegerField(default=0, verbose_name="AI requests"),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_analytics",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "monthly analytics",
                "verbose_name_plural": "monthly analytics",
                "db_table": "monthly_analytics",
                "ordering": ["-year", "-month"],
                "unique_together": {("mover", "year", "month")},
            },
        ),
    ]
