# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="quote number"
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="validity days"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="valid until"),
                ),
                (
                    "items_data",
                    models.JSONField(
                        default=list,
                        help_text="Snapshot of order items at quote creation",
                        verbose_name="items data",
                    ),
                ),
                (
                    "pricing_data",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of pricing breakdown",
                        verbose_name="pricing data",
                    ),
                ),
                (
                    "custom_notes",
                    models.TextField(blank=True, verbose_name="custom notes"),
                ),
                (
                    "custom_notes_he",
                    models.TextField(blank=True, verbose_name="custom notes (Hebrew)"),
                ),
                (
                    "discount_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="discount description"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total amount",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "sent_to_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="sent to email"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="viewed at"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quotes/pdfs/",
                        verbose_name="PDF file",
                    ),
                ),
                (
                    "pdf_generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="PDF generated at"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote",
                "verbose_name_plural": "quotes",
                "db_table": "quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="item name")),
                (
                    "name_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="item name (Hebrew)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="unit price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="total price"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotes.quote",
                        verbose_name="quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote item",
                "verbose_name_plural": "quote items",
                "db_table": "quote_items",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuoteTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="template name"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="is default"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "header_text",
                    models.TextField(blank=True, verbose_name="header text"),
                ),
                (
                    "header_text_he",
                    models.TextField(blank=True, verbose_name="header text (Hebrew)"),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="footer text"),
                ),
                (
                    "footer_text_he",
                    models.TextField(blank=True, verbose_name="footer text (Hebrew)"),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="terms and conditions"),
                ),
                (
                    "terms_and_conditions_he",
                    models.TextField(
                        blank=True, verbose_name="terms and conditions (Hebrew)"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3b82f6", max_length=7, verbose_name="primary color"
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1e40af", max_length=7, verbose_name="secondary color"
                    ),
                ),
                (
                    "logo_position",
                    models.CharField(
                        choices=[
                            ("top-left", "Top Left"),
                            ("top-center", "Top Center"),
                            ("top-right", "Top Right"),
                        ],
                        default="top-right",
                        max_length=20,
                        verbose_name="logo position",
                    ),
                ),
                (
                    "show_company_details",
                    models.BooleanField(
                        default=True, verbose_name="show company details"
                    ),
                ),
                (
                    "show_item_breakdown",
                    models.BooleanField(
                        default=True, verbose_name="show item breakdown"
                    ),
                ),
                (
                    "show_pricing_factors",
                    models.BooleanField(
                        default=False, verbose_name="show pricing factors"
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_templates",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "quote template",
                "verbose_name_plural": "quote templates",
                "db_table": "quote_templates",
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to="quotes.quotetemplate",
                verbose_name="template",
            ),
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "signature_data",
                    models.TextField(
                        help_text="Base64 encoded signature image",
                        verbose_name="signature data",
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(max_length=255, verbose_name="signer name"),
                ),
                (
                    "signer_email",
                    models.EmailField(max_length=254, verbose_name="signer email"),
                ),
                (
                    "signer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="signer phone"
                    ),
                ),
                (
                    "signer_id_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="signer ID number"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="signed at"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "verification_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="verification code"
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="quotes.quote",
                        verbose_name="quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "signature",
                "verbose_name_plural": "signatures",
                "db_table": "signatures",
            },
        ),
    ]
