# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., order_created, quote_sent, booking_reminder",
                        max_length=50,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "name_he",
                    models.CharField(max_length=100, verbose_name="name (Hebrew)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "default_email",
                    models.BooleanField(default=True, verbose_name="email by default"),
                ),
                (
                    "default_sms",
                    models.BooleanField(default=False, verbose_name="SMS by default"),
                ),
                (
                    "default_push",
                    models.BooleanField(default=True, verbose_name="push by default"),
                ),
                (
                    "email_template",
                    models.CharField(
                        blank=True,
                        help_text="Template name for email",
                        max_length=100,
                        verbose_name="email template",
                    ),
                ),
                (
                    "sms_template",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SMS template"
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Critical notifications cannot be disabled",
                        verbose_name="is critical",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "notification type",
                "verbose_name_plural": "notification types",
                "db_table": "notification_types",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "to_email",
                    models.EmailField(max_length=254, verbose_name="to email"),
                ),
                (
                    "from_email",
                    models.EmailField(max_length=254, verbose_name="from email"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("body_html", models.TextField(blank=True, verbose_name="HTML body")),
                ("body_text", models.TextField(blank=True, verbose_name="text body")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="opened at"
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external message ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="retry count"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="notifications.notificationtype",
                        verbose_name="notification type",
                    ),
                ),
            ],
            options={
                "verbose_name": "email log",
                "verbose_name_plural": "email logs",
                "db_table": "email_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("to_phone", models.CharField(max_length=20, verbose_name="to phone")),
                (
                    "from_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="from phone"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external message ID"
                    ),
                ),
                (
                    "segments",
                    models.PositiveIntegerField(default=1, verbose_name="segments"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="cost",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="error code"
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="notifications.notificationtype",
                        verbose_name="notification type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS log",
                "verbose_name_plural": "SMS logs",
                "db_table": "sms_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="email enabled"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS enabled"),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="push enabled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="notifications.notificationtype",
                        verbose_name="notification type",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "notification_preferences",
                "unique_together": {("user", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "title_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="title (Hebrew)"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "message_he",
                    models.TextField(blank=True, verbose_name="message (Hebrew)"),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to navigate when notification is clicked",
                        max_length=500,
                        verbose_name="action URL",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="additional data"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtype",
                        verbose_name="notification type",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_a4dd5c_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7336fd_idx",
                    ),
                ],
            },
        ),
    ]
