# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="name (English)"),
                ),
                (
                    "name_he",
                    models.CharField(max_length=255, verbose_name="name (Hebrew)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="description (English)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="description (Hebrew)"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Icon identifier (e.g., "sofa", "tv")',
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="movers.itemcategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "item category",
                "verbose_name_plural": "item categories",
                "db_table": "item_categories",
                "ordering": ["display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="name (English)"),
                ),
                (
                    "name_he",
                    models.CharField(max_length=255, verbose_name="name (Hebrew)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="description (English)"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="description (Hebrew)"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="icon"),
                ),
                (
                    "default_base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default price in ILS",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="default base price",
                    ),
                ),
                (
                    "default_assembly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="default assembly price",
                    ),
                ),
                (
                    "default_disassembly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="default disassembly price",
                    ),
                ),
                (
                    "default_special_handling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="default special handling price",
                    ),
                ),
                (
                    "requires_assembly",
                    models.BooleanField(
                        default=False, verbose_name="typically requires assembly"
                    ),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False,
                        verbose_name="typically requires special handling",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(
                        default=False, verbose_name="typically fragile"
                    ),
                ),
                (
                    "weight_class",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("extra_heavy", "Extra Heavy"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="weight class",
                    ),
                ),
                (
                    "average_dimensions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Average dimensions in cm: {"length": 0, "width": 0, "height": 0}',
                        verbose_name="average dimensions",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="movers.itemcategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "item type",
                "verbose_name_plural": "item types",
                "db_table": "item_types",
                "ordering": ["category", "display_order", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="PricingFactors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "floor_surcharge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Additional percentage per floor (e.g., 5% per floor)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="floor surcharge (%)",
                    ),
                ),
                (
                    "ground_floor_number",
                    models.IntegerField(
                        default=0,
                        help_text="Which floor is considered ground (0 or 1)",
                        verbose_name="ground floor number",
                    ),
                ),
                (
                    "elevator_discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Discount on floor surcharge if elevator available",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="elevator discount (%)",
                    ),
                ),
                (
                    "distance_surcharge_per_10m",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Additional cost per 10 meters from truck to building entrance",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="distance surcharge per 10m",
                    ),
                ),
                (
                    "travel_distance_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Cost per kilometer between origin and destination",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="travel cost per km",
                    ),
                ),
                (
                    "minimum_travel_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="minimum travel charge",
                    ),
                ),
                (
                    "peak_season_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.25"),
                        help_text="Price multiplier for peak season (July-August)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="peak season multiplier",
                    ),
                ),
                (
                    "peak_months",
                    models.JSONField(
                        default=list,
                        help_text="List of peak month numbers [7, 8] for July-August",
                        verbose_name="peak months",
                    ),
                ),
                (
                    "weekend_surcharge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="weekend surcharge (%)",
                    ),
                ),
                (
                    "friday_surcharge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Friday surcharge (%)",
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="minimum order amount",
                    ),
                ),
                (
                    "early_morning_surcharge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Surcharge for orders before 8 AM",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="early morning surcharge (%)",
                    ),
                ),
                (
                    "evening_surcharge_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Surcharge for orders after 6 PM",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="evening surcharge (%)",
                    ),
                ),
                (
                    "mover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_factors",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "pricing factors",
                "verbose_name_plural": "pricing factors",
                "db_table": "pricing_factors",
            },
        ),
        migrations.CreateModel(
            name="MoverPricing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit in ILS",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="base price",
                    ),
                ),
                (
                    "assembly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="assembly price",
                    ),
                ),
                (
                    "disassembly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="disassembly price",
                    ),
                ),
                (
                    "special_handling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="special handling price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is offered by the mover",
                        verbose_name="active",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mover_prices",
                        to="movers.itemtype",
                        verbose_name="item type",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "mover pricing",
                "verbose_name_plural": "mover pricing",
                "db_table": "mover_pricing",
                "ordering": ["item_type__category", "item_type__display_order"],
                "unique_together": {("mover", "item_type")},
            },
        ),
    ]
