# Generated by Django 5.0.14 on 2026-01-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movers", "0003_itemtypeattribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemtypeattribute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="itemtypeattribute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
