# Generated by Django 5.0.14 on 2026-02-13 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("movers", "0004_alter_itemtypeattribute_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtypesuggestion",
            name="occurrence_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many times this item was requested by customers",
                verbose_name="occurrence count",
            ),
        ),
        migrations.AddField(
            model_name="itemtypesuggestion",
            name="source",
            field=models.CharField(
                choices=[("mover", "Mover"), ("auto", "Auto-detected from order")],
                default="auto",
                max_length=20,
                verbose_name="source",
            ),
        ),
        migrations.AlterField(
            model_name="itemtypesuggestion",
            name="suggested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_suggestions",
                to="accounts.moverprofile",
                verbose_name="suggested by",
            ),
        ),
    ]
