# Generated by Django 5.0.14 on 2026-02-13 11:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movers", "0005_add_suggestion_source_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingfactors",
            name="distance_surcharge_per_10m",
        ),
        migrations.AddField(
            model_name="pricingfactors",
            name="distance_surcharge_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Percentage of items subtotal charged per 10 meters from truck to building",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="distance surcharge (%)",
            ),
        ),
    ]
