# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("movers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("quoted", "Quoted"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "original_description",
                    models.TextField(
                        help_text="Customer's free-text description of items to move",
                        verbose_name="original description",
                    ),
                ),
                ("origin_address", models.TextField(verbose_name="origin address")),
                (
                    "origin_city",
                    models.CharField(max_length=100, verbose_name="origin city"),
                ),
                (
                    "origin_floor",
                    models.IntegerField(default=0, verbose_name="origin floor"),
                ),
                (
                    "origin_has_elevator",
                    models.BooleanField(
                        default=False, verbose_name="origin has elevator"
                    ),
                ),
                (
                    "origin_building_floors",
                    models.IntegerField(
                        default=1, verbose_name="origin building floors"
                    ),
                ),
                (
                    "origin_distance_to_truck",
                    models.IntegerField(
                        default=0,
                        help_text="Distance from building entrance to truck parking in meters",
                        verbose_name="origin distance to truck (m)",
                    ),
                ),
                (
                    "origin_coordinates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"lat": 0.0, "lng": 0.0}',
                        verbose_name="origin coordinates",
                    ),
                ),
                (
                    "destination_address",
                    models.TextField(verbose_name="destination address"),
                ),
                (
                    "destination_city",
                    models.CharField(max_length=100, verbose_name="destination city"),
                ),
                (
                    "destination_floor",
                    models.IntegerField(default=0, verbose_name="destination floor"),
                ),
                (
                    "destination_has_elevator",
                    models.BooleanField(
                        default=False, verbose_name="destination has elevator"
                    ),
                ),
                (
                    "destination_building_floors",
                    models.IntegerField(
                        default=1, verbose_name="destination building floors"
                    ),
                ),
                (
                    "destination_distance_to_truck",
                    models.IntegerField(
                        default=0, verbose_name="destination distance to truck (m)"
                    ),
                ),
                (
                    "destination_coordinates",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="destination coordinates"
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Distance between origin and destination",
                        max_digits=10,
                        verbose_name="distance (km)",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(
                        default=0, verbose_name="estimated travel duration (minutes)"
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="preferred date"
                    ),
                ),
                (
                    "preferred_time_slot",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "morning", "afternoon", "08:00-12:00"',
                        max_length=50,
                        verbose_name="preferred time slot",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="scheduled date"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="scheduled time"
                    ),
                ),
                (
                    "items_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="items subtotal",
                    ),
                ),
                (
                    "origin_floor_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="origin floor surcharge",
                    ),
                ),
                (
                    "destination_floor_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="destination floor surcharge",
                    ),
                ),
                (
                    "distance_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Surcharge for distance from truck to building",
                        max_digits=12,
                        verbose_name="distance surcharge",
                    ),
                ),
                (
                    "travel_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost for travel between locations",
                        max_digits=12,
                        verbose_name="travel cost",
                    ),
                ),
                (
                    "seasonal_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="seasonal adjustment",
                    ),
                ),
                (
                    "day_of_week_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weekend/Friday surcharge",
                        max_digits=12,
                        verbose_name="day of week adjustment",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="discount",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total price",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        default=list,
                        help_text="List of image URLs",
                        verbose_name="images",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="customer notes"),
                ),
                (
                    "mover_notes",
                    models.TextField(blank=True, verbose_name="mover notes"),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private notes for admin/mover",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "ai_processed",
                    models.BooleanField(default=False, verbose_name="AI processed"),
                ),
                (
                    "ai_processing_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI processing data"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("image_url", models.URLField(verbose_name="image URL")),
                ("filename", models.CharField(max_length=255, verbose_name="filename")),
                (
                    "room_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="room name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "ai_analyzed",
                    models.BooleanField(default=False, verbose_name="AI analyzed"),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI analysis"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_images",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order image",
                "verbose_name_plural": "order images",
                "db_table": "order_images",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="name (Hebrew)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "requires_assembly",
                    models.BooleanField(
                        default=False, verbose_name="requires assembly"
                    ),
                ),
                (
                    "requires_disassembly",
                    models.BooleanField(
                        default=False, verbose_name="requires disassembly"
                    ),
                ),
                (
                    "requires_special_handling",
                    models.BooleanField(
                        default=False, verbose_name="requires special handling"
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(default=False, verbose_name="is fragile"),
                ),
                (
                    "room_name",
                    models.CharField(
                        blank=True,
                        help_text='e.g., "Living Room", "Bedroom 1"',
                        max_length=100,
                        verbose_name="room name",
                    ),
                ),
                (
                    "room_floor",
                    models.IntegerField(
                        default=0,
                        help_text="Floor within the building",
                        verbose_name="room floor",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="unit price",
                    ),
                ),
                (
                    "assembly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="assembly cost",
                    ),
                ),
                (
                    "disassembly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="disassembly cost",
                    ),
                ),
                (
                    "special_handling_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="special handling cost",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total price",
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="AI confidence score (0-1)",
                        max_digits=4,
                        verbose_name="AI confidence",
                    ),
                ),
                (
                    "ai_needs_clarification",
                    models.BooleanField(
                        default=False, verbose_name="needs clarification"
                    ),
                ),
                (
                    "ai_clarification_question",
                    models.TextField(blank=True, verbose_name="clarification question"),
                ),
                (
                    "ai_matched_item_type",
                    models.BooleanField(
                        default=False,
                        help_text="Whether AI matched this to a known item type",
                        verbose_name="matched to item type",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="movers.itemtype",
                        verbose_name="item type",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "db_table": "order_items",
                "ordering": ["room_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("answer", "Answer"),
                            ("analysis", "Analysis"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="message type",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "content_he",
                    models.TextField(blank=True, verbose_name="content (Hebrew)"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "related_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="orders.orderitem",
                        verbose_name="related item",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI conversation",
                "verbose_name_plural": "AI conversations",
                "db_table": "ai_conversations",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["mover", "status"], name="orders_mover_i_c18aa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_custome_58f6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["scheduled_date"], name="orders_schedul_6df871_idx"
            ),
        ),
    ]
