# Generated by Django 5.0.14 on 2026-01-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.moverprofile",
                verbose_name="mover",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="original_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Customer's free-text description of items to move",
                verbose_name="original description",
            ),
        ),
    ]
