# Generated by Django 5.0.14 on 2026-02-07 22:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0002_alter_order_mover_alter_order_original_description"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("comparing", "Comparing"),
                    ("quoted", "Quoted"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="ComparisonEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("rank", models.PositiveIntegerField(default=0, verbose_name="rank")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="total price",
                    ),
                ),
                (
                    "pricing_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Full pricing snapshot from PriceAnalyzerService",
                        verbose_name="pricing breakdown",
                    ),
                ),
                (
                    "mover_company_name",
                    models.CharField(max_length=255, verbose_name="company name"),
                ),
                (
                    "mover_company_name_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="company name (Hebrew)"
                    ),
                ),
                (
                    "mover_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="rating",
                    ),
                ),
                (
                    "mover_total_reviews",
                    models.IntegerField(default=0, verbose_name="total reviews"),
                ),
                (
                    "mover_completed_orders",
                    models.IntegerField(default=0, verbose_name="completed orders"),
                ),
                (
                    "mover_is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "mover_logo_url",
                    models.URLField(blank=True, verbose_name="logo URL"),
                ),
                (
                    "used_custom_pricing",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this mover has custom pricing set up",
                        verbose_name="used custom pricing",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculated", "Calculated"),
                            ("fallback", "Fallback"),
                            ("error", "Error"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        default="calculated",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_entries",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comparison_entry",
                        to="quotes.quote",
                        verbose_name="quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "comparison entry",
                "verbose_name_plural": "comparison entries",
                "db_table": "comparison_entries",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="OrderComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("selected", "Selected"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "total_eligible_movers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total eligible movers"
                    ),
                ),
                (
                    "total_priced_movers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total priced movers"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "selected_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.comparisonentry",
                        verbose_name="selected entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "order comparison",
                "verbose_name_plural": "order comparisons",
                "db_table": "order_comparisons",
            },
        ),
        migrations.AddField(
            model_name="comparisonentry",
            name="comparison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="orders.ordercomparison",
                verbose_name="comparison",
            ),
        ),
    ]
