# Generated by Django 5.0.14 on 2026-02-14 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_mover_geo_fields"),
        ("orders", "0003_alter_order_status_comparisonentry_ordercomparison_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_flexibility",
            field=models.CharField(
                choices=[("specific", "Specific Date"), ("range", "Date Range")],
                default="specific",
                help_text="Whether customer wants a specific date or a date range",
                max_length=20,
                verbose_name="date flexibility",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="preferred_date_end",
            field=models.DateField(
                blank=True,
                help_text='End date for date range preference. Only used when date_flexibility is "range".',
                null=True,
                verbose_name="preferred date end",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["preferred_date", "preferred_date_end"],
                name="orders_preferr_225894_idx",
            ),
        ),
    ]
