# Generated by Django 5.0.14 on 2026-02-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="estimated_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("extra_large", "Extra Large"),
                ],
                default="medium",
                help_text="AI-estimated size for pricing unmatched items",
                max_length=20,
                verbose_name="estimated size",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="estimated_weight_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("light", "Light"),
                    ("medium", "Medium"),
                    ("heavy", "Heavy"),
                    ("extra_heavy", "Extra Heavy"),
                ],
                default="medium",
                help_text="AI-estimated weight class for pricing unmatched items",
                max_length=20,
                verbose_name="estimated weight class",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
