# Generated by Django 5.0.14 on 2025-12-27 17:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("mover", "Mover"),
                            ("customer", "Customer"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="user type",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("he", "Hebrew"), ("en", "English")],
                        default="he",
                        max_length=2,
                        verbose_name="preferred language",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="email verified"),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="phone verified"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "verification_code",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="verification code"
                    ),
                ),
                (
                    "verification_code_expires",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verification code expires"
                    ),
                ),
                (
                    "verification_attempts",
                    models.IntegerField(
                        default=0, verbose_name="verification attempts"
                    ),
                ),
                (
                    "spam_score",
                    models.IntegerField(
                        default=0,
                        help_text="Higher score = more likely spam",
                        verbose_name="spam score",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="total orders"),
                ),
                (
                    "default_address",
                    models.TextField(blank=True, verbose_name="default address"),
                ),
                (
                    "default_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="default city"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "customer profile",
                "verbose_name_plural": "customer profiles",
                "db_table": "customer_profiles",
            },
        ),
        migrations.CreateModel(
            name="MoverProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="company name"),
                ),
                (
                    "company_name_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="company name (Hebrew)"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="license number"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=20, verbose_name="tax ID"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "service_areas",
                    models.JSONField(
                        default=list,
                        help_text="List of cities/regions the mover serves",
                        verbose_name="service areas",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mover_logos/",
                        verbose_name="logo",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="description (Hebrew)"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Admin verified business",
                        verbose_name="verified",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="total reviews"),
                ),
                (
                    "completed_orders",
                    models.IntegerField(default=0, verbose_name="completed orders"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Mover is accepting new orders",
                        verbose_name="active",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mover_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mover profile",
                "verbose_name_plural": "mover profiles",
                "db_table": "mover_profiles",
            },
        ),
    ]
