# Generated by Django 5.0.14 on 2026-02-13 00:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moverprofile",
            name="base_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude of mover base location",
                max_digits=10,
                null=True,
                verbose_name="base latitude",
            ),
        ),
        migrations.AddField(
            model_name="moverprofile",
            name="base_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude of mover base location",
                max_digits=10,
                null=True,
                verbose_name="base longitude",
            ),
        ),
        migrations.AddField(
            model_name="moverprofile",
            name="service_radius_km",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("50.0"),
                help_text="Maximum radius in km from base location for pickup",
                max_digits=6,
                verbose_name="service radius (km)",
            ),
        ),
        migrations.AlterField(
            model_name="moverprofile",
            name="service_areas",
            field=models.JSONField(
                default=list,
                help_text="List of cities/regions the mover serves (legacy)",
                verbose_name="service areas",
            ),
        ),
    ]
