# Generated by Django 5.0.14 on 2026-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_moverprofile_approval_onboarding"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="moverprofile",
            name="direct_link_code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for the mover direct order link",
                max_length=12,
                null=True,
                unique=True,
                verbose_name="direct link code",
            ),
        ),
        migrations.AddField(
            model_name="moverprofile",
            name="direct_link_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow customers to create orders directly for this mover",
                verbose_name="direct link enabled",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("phone", ""), _negated=True),
                    models.Q(("phone", "0556637120"), _negated=True),
                ),
                fields=("phone",),
                name="unique_phone_except_test",
            ),
        ),
    ]
