# Generated by Django 5.0.14 on 2025-12-27 17:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="plan name")),
                (
                    "name_he",
                    models.CharField(max_length=50, verbose_name="plan name (Hebrew)"),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="plan type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="description (Hebrew)"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="monthly price",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discounted yearly price",
                        max_digits=10,
                        verbose_name="yearly price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ILS", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "max_orders_per_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited",
                        null=True,
                        verbose_name="max orders per month",
                    ),
                ),
                (
                    "max_quotes_per_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="max quotes per month"
                    ),
                ),
                (
                    "has_ai_parsing",
                    models.BooleanField(default=False, verbose_name="AI item parsing"),
                ),
                (
                    "has_ai_images",
                    models.BooleanField(
                        default=False, verbose_name="AI image analysis"
                    ),
                ),
                (
                    "has_digital_signatures",
                    models.BooleanField(
                        default=False, verbose_name="digital signatures"
                    ),
                ),
                (
                    "has_sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="SMS notifications"
                    ),
                ),
                (
                    "has_advanced_analytics",
                    models.BooleanField(
                        default=False, verbose_name="advanced analytics"
                    ),
                ),
                (
                    "has_priority_support",
                    models.BooleanField(default=False, verbose_name="priority support"),
                ),
                (
                    "has_custom_branding",
                    models.BooleanField(default=False, verbose_name="custom branding"),
                ),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="API access"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this plan as popular",
                        verbose_name="is popular",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription plan",
                "verbose_name_plural": "subscription plans",
                "db_table": "subscription_plans",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        default="credit_card",
                        max_length=20,
                        verbose_name="method type",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="is default"),
                ),
                (
                    "last_four_digits",
                    models.CharField(max_length=4, verbose_name="last 4 digits"),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="card brand"
                    ),
                ),
                (
                    "expiry_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="expiry month"
                    ),
                ),
                (
                    "expiry_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="expiry year"
                    ),
                ),
                (
                    "external_token",
                    models.CharField(
                        help_text="Tokenized card from payment provider",
                        max_length=255,
                        verbose_name="external token",
                    ),
                ),
                (
                    "external_payment_method_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="external payment method ID",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="billing name"
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="billing email"
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                        verbose_name="billing cycle",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="current period start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="current period end"),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="trial end"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "external_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from payment provider (Stripe, Tranzila, etc.)",
                        max_length=255,
                        verbose_name="external subscription ID",
                    ),
                ),
                (
                    "external_customer_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external customer ID"
                    ),
                ),
                (
                    "orders_used_this_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="orders used this month"
                    ),
                ),
                (
                    "quotes_used_this_month",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quotes used this month"
                    ),
                ),
                (
                    "usage_reset_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="usage reset date"
                    ),
                ),
                (
                    "mover",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="payments.subscriptionplan",
                        verbose_name="plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="ILS", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("one_time", "One Time"),
                            ("refund", "Refund"),
                        ],
                        default="subscription",
                        max_length=20,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., credit_card, bank_transfer",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "last_four_digits",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="last 4 digits"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="card brand"
                    ),
                ),
                (
                    "external_payment_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external payment ID"
                    ),
                ),
                (
                    "external_invoice_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="external invoice ID"
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="billing email"
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="billing name"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="refunded at"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="refund amount",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, verbose_name="refund reason"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="error code"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="payments/invoices/",
                        verbose_name="invoice PDF",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="payments.subscription",
                        verbose_name="subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="coupon code"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                        verbose_name="discount value",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="valid from")),
                ("valid_until", models.DateTimeField(verbose_name="valid until")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave empty for unlimited",
                        null=True,
                        verbose_name="max uses",
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(default=0, verbose_name="times used"),
                ),
                (
                    "first_time_only",
                    models.BooleanField(
                        default=False, verbose_name="first time subscribers only"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty for all plans",
                        related_name="coupons",
                        to="payments.subscriptionplan",
                        verbose_name="applicable plans",
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
                "db_table": "coupons",
            },
        ),
    ]
