# Generated by Django 5.0.14 on 2025-12-27 17:55

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "block_type",
                    models.CharField(
                        choices=[("full_day", "Full Day"), ("partial", "Partial Day")],
                        default="full_day",
                        max_length=20,
                        verbose_name="block type",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Required for partial day blocks",
                        null=True,
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Required for partial day blocks",
                        null=True,
                        verbose_name="end time",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="reason"),
                ),
                (
                    "is_recurring_yearly",
                    models.BooleanField(
                        default=False,
                        help_text="Block this date every year (e.g., holidays)",
                        verbose_name="recurring yearly",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "blocked date",
                "verbose_name_plural": "blocked dates",
                "db_table": "blocked_dates",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                (
                    "scheduled_start_time",
                    models.TimeField(verbose_name="scheduled start time"),
                ),
                (
                    "scheduled_end_time",
                    models.TimeField(
                        blank=True,
                        help_text="Estimated end time",
                        null=True,
                        verbose_name="scheduled end time",
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=2,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0.5)],
                        verbose_name="estimated duration (hours)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tentative", "Tentative"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="tentative",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="actual start time"
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="actual end time"
                    ),
                ),
                (
                    "crew_size",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="crew size",
                    ),
                ),
                (
                    "crew_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for the crew",
                        verbose_name="crew notes",
                    ),
                ),
                (
                    "customer_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="customer confirmed"
                    ),
                ),
                (
                    "customer_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="customer confirmed at"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="reminder sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reminder sent at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cancelled by",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
                "db_table": "bookings",
                "ordering": ["scheduled_date", "scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("both", "Both")],
                        default="email",
                        max_length=10,
                        verbose_name="reminder type",
                    ),
                ),
                ("scheduled_for", models.DateTimeField(verbose_name="scheduled for")),
                ("sent", models.BooleanField(default=False, verbose_name="sent")),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email or phone number",
                        max_length=255,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="scheduling.booking",
                        verbose_name="booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking reminder",
                "verbose_name_plural": "booking reminders",
                "db_table": "booking_reminders",
                "ordering": ["scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g., "Morning", "Afternoon", "Evening"',
                        max_length=50,
                        verbose_name="slot name",
                    ),
                ),
                (
                    "name_he",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="slot name (Hebrew)"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "time slot",
                "verbose_name_plural": "time slots",
                "db_table": "time_slots",
                "ordering": ["display_order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                        verbose_name="day of week",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="start time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.time(18, 0), verbose_name="end time"
                    ),
                ),
                (
                    "max_bookings",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of bookings allowed for this day",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="maximum bookings",
                    ),
                ),
                (
                    "mover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="accounts.moverprofile",
                        verbose_name="mover",
                    ),
                ),
            ],
            options={
                "verbose_name": "weekly availability",
                "verbose_name_plural": "weekly availabilities",
                "db_table": "weekly_availability",
                "ordering": ["day_of_week"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["mover", "scheduled_date"], name="bookings_mover_i_532452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyavailability",
            unique_together={("mover", "day_of_week")},
        ),
    ]
